#############################################################################
# Makefile for building: CurrentDriveCheckout
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Jun 4 12:39:05 2014
# Project:  CurrentDriveCheckout.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile CurrentDriveCheckout.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -std=c++0x -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/usr/include/flycapture -I/usr/local/include/eigen3 -I/usr/local/include -I/usr/include -I/usr/local/DAQ -I/usr/local/include/usbhid -I/usr/include/gsl -I../Sandbox -I/usr/X11R6/include -IBIN -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -L/usr/local/DAQ -L/usr/local/lib -L/usr/lib -L../OmnimagnetLibs/AD_IO_Lib -L../OmnimagnetLibs/Math_Lib -L../OmnimagnetLibs/Producer_Lib -lopencv_imgproc -lopencv_highgui -lopencv_core -lopencv_calib3d -lopencv_video -ls626 -lflycapture -lcomedi -lmccusb -lAD_IO -lMath -lProducer -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = BIN/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		../Sandbox/GUI/InterfaceButtons.cpp \
		../Sandbox/GUI/NumberWithUnits.cpp \
		../Sandbox/Devices/AMC_30A8.cpp \
		../Sandbox/Devices/Advantech_PCI_1724U_ADIO.cpp \
		../Sandbox/Devices/Advantech_PCI_1724U.cpp \
		../Sandbox/Devices/MultipleOmnimagnetSetup.cpp \
		../Sandbox/Devices/Omnimagnet.cpp BIN/moc_mainwindow.cpp \
		BIN/moc_InterfaceButtons.cpp \
		BIN/moc_NumberWithUnits.cpp
OBJECTS       = BIN/main.o \
		BIN/mainwindow.o \
		BIN/InterfaceButtons.o \
		BIN/NumberWithUnits.o \
		BIN/AMC_30A8.o \
		BIN/Advantech_PCI_1724U_ADIO.o \
		BIN/Advantech_PCI_1724U.o \
		BIN/MultipleOmnimagnetSetup.o \
		BIN/Omnimagnet.o \
		BIN/moc_mainwindow.o \
		BIN/moc_InterfaceButtons.o \
		BIN/moc_NumberWithUnits.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CurrentDriveCheckout.pro
QMAKE_TARGET  = CurrentDriveCheckout
DESTDIR       = 
TARGET        = CurrentDriveCheckout

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: CurrentDriveCheckout.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile CurrentDriveCheckout.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile CurrentDriveCheckout.pro

dist: 
	@$(CHK_DIR_EXISTS) BIN/CurrentDriveCheckout1.0.0 || $(MKDIR) BIN/CurrentDriveCheckout1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) BIN/CurrentDriveCheckout1.0.0/ && $(COPY_FILE) --parents mainwindow.h ../Sandbox/GUI/InterfaceButtons.h ../Sandbox/GUI/NumberWithUnits.h ../Sandbox/Devices/AMC_30A8.h ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h ../Sandbox/Devices/Advantech_PCI_1724U.h ../Sandbox/Utilities/utilities.h ../Sandbox/Devices/MultipleOmnimagnetSetup.h ../Sandbox/Devices/Omnimagnet.h ../Sandbox/Utilities/Math.h ../Sandbox/Producers/Producers.h BIN/CurrentDriveCheckout1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp ../Sandbox/GUI/InterfaceButtons.cpp ../Sandbox/GUI/NumberWithUnits.cpp ../Sandbox/Devices/AMC_30A8.cpp ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.cpp ../Sandbox/Devices/Advantech_PCI_1724U.cpp ../Sandbox/Devices/MultipleOmnimagnetSetup.cpp ../Sandbox/Devices/Omnimagnet.cpp BIN/CurrentDriveCheckout1.0.0/ && $(COPY_FILE) --parents mainwindow.ui BIN/CurrentDriveCheckout1.0.0/ && (cd `dirname BIN/CurrentDriveCheckout1.0.0` && $(TAR) CurrentDriveCheckout1.0.0.tar CurrentDriveCheckout1.0.0 && $(COMPRESS) CurrentDriveCheckout1.0.0.tar) && $(MOVE) `dirname BIN/CurrentDriveCheckout1.0.0`/CurrentDriveCheckout1.0.0.tar.gz . && $(DEL_FILE) -r BIN/CurrentDriveCheckout1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: BIN/moc_mainwindow.cpp BIN/moc_InterfaceButtons.cpp BIN/moc_NumberWithUnits.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) BIN/moc_mainwindow.cpp BIN/moc_InterfaceButtons.cpp BIN/moc_NumberWithUnits.cpp
BIN/moc_mainwindow.cpp: ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h \
		../Sandbox/Devices/Advantech_PCI_1724U.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h \
		../Sandbox/Devices/AMC_30A8.h \
		../Sandbox/Devices/MultipleOmnimagnetSetup.h \
		../Sandbox/Devices/Omnimagnet.h \
		../Sandbox/Utilities/Magnetics.h \
		../Sandbox/Producers/FieldProducer.h \
		../Sandbox/Producers/ConstMomentFieldProducer.h \
		../Sandbox/Producers/MomentProducer.h \
		../Sandbox/Producers/RotatingMomentProducer.h \
		../Sandbox/Producers/Configuration6DOF_Producer.h \
		../Sandbox/Producers/PositionProducer.h \
		../Sandbox/Producers/OrientationProducer.h \
		../Sandbox/Producers/VectorTemperature_Producer.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o BIN/moc_mainwindow.cpp

BIN/moc_InterfaceButtons.cpp: ../Sandbox/GUI/InterfaceButtons.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../Sandbox/GUI/InterfaceButtons.h -o BIN/moc_InterfaceButtons.cpp

BIN/moc_NumberWithUnits.cpp: ../Sandbox/GUI/NumberWithUnits.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../Sandbox/GUI/NumberWithUnits.h -o BIN/moc_NumberWithUnits.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../Sandbox/GUI/InterfaceButtons.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

BIN/main.o: main.cpp mainwindow.h \
		../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h \
		../Sandbox/Devices/Advantech_PCI_1724U.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h \
		../Sandbox/Devices/AMC_30A8.h \
		../Sandbox/Devices/MultipleOmnimagnetSetup.h \
		../Sandbox/Devices/Omnimagnet.h \
		../Sandbox/Utilities/Magnetics.h \
		../Sandbox/Producers/FieldProducer.h \
		../Sandbox/Producers/ConstMomentFieldProducer.h \
		../Sandbox/Producers/MomentProducer.h \
		../Sandbox/Producers/RotatingMomentProducer.h \
		../Sandbox/Producers/Configuration6DOF_Producer.h \
		../Sandbox/Producers/PositionProducer.h \
		../Sandbox/Producers/OrientationProducer.h \
		../Sandbox/Producers/VectorTemperature_Producer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/main.o main.cpp

BIN/mainwindow.o: mainwindow.cpp mainwindow.h \
		../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h \
		../Sandbox/Devices/Advantech_PCI_1724U.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h \
		../Sandbox/Devices/AMC_30A8.h \
		../Sandbox/Devices/MultipleOmnimagnetSetup.h \
		../Sandbox/Devices/Omnimagnet.h \
		../Sandbox/Utilities/Magnetics.h \
		../Sandbox/Producers/FieldProducer.h \
		../Sandbox/Producers/ConstMomentFieldProducer.h \
		../Sandbox/Producers/MomentProducer.h \
		../Sandbox/Producers/RotatingMomentProducer.h \
		../Sandbox/Producers/Configuration6DOF_Producer.h \
		../Sandbox/Producers/PositionProducer.h \
		../Sandbox/Producers/OrientationProducer.h \
		../Sandbox/Producers/VectorTemperature_Producer.h \
		ui_mainwindow.h \
		../Sandbox/GUI/InterfaceButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/mainwindow.o mainwindow.cpp

BIN/InterfaceButtons.o: ../Sandbox/GUI/InterfaceButtons.cpp ../Sandbox/GUI/InterfaceButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/InterfaceButtons.o ../Sandbox/GUI/InterfaceButtons.cpp

BIN/NumberWithUnits.o: ../Sandbox/GUI/NumberWithUnits.cpp ../Sandbox/GUI/NumberWithUnits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/NumberWithUnits.o ../Sandbox/GUI/NumberWithUnits.cpp

BIN/AMC_30A8.o: ../Sandbox/Devices/AMC_30A8.cpp ../Sandbox/Devices/AMC_30A8.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/AMC_30A8.o ../Sandbox/Devices/AMC_30A8.cpp

BIN/Advantech_PCI_1724U_ADIO.o: ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.cpp ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h \
		../Sandbox/Devices/Advantech_PCI_1724U.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/Advantech_PCI_1724U_ADIO.o ../Sandbox/Devices/Advantech_PCI_1724U_ADIO.cpp

BIN/Advantech_PCI_1724U.o: ../Sandbox/Devices/Advantech_PCI_1724U.cpp ../Sandbox/Devices/Advantech_PCI_1724U.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/Advantech_PCI_1724U.o ../Sandbox/Devices/Advantech_PCI_1724U.cpp

BIN/MultipleOmnimagnetSetup.o: ../Sandbox/Devices/MultipleOmnimagnetSetup.cpp ../Sandbox/Devices/MultipleOmnimagnetSetup.h \
		../Sandbox/Devices/Omnimagnet.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h \
		../Sandbox/Utilities/Magnetics.h \
		../Sandbox/Producers/FieldProducer.h \
		../Sandbox/Producers/ConstMomentFieldProducer.h \
		../Sandbox/Producers/MomentProducer.h \
		../Sandbox/Producers/RotatingMomentProducer.h \
		../Sandbox/Producers/Configuration6DOF_Producer.h \
		../Sandbox/Producers/PositionProducer.h \
		../Sandbox/Producers/OrientationProducer.h \
		../Sandbox/Producers/VectorTemperature_Producer.h \
		../Sandbox/Devices/Advantech_PCI_1724U_ADIO.h \
		../Sandbox/Devices/Advantech_PCI_1724U.h \
		../Sandbox/Devices/AMC_30A8.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/MultipleOmnimagnetSetup.o ../Sandbox/Devices/MultipleOmnimagnetSetup.cpp

BIN/Omnimagnet.o: ../Sandbox/Devices/Omnimagnet.cpp ../Sandbox/Devices/Omnimagnet.h \
		../Sandbox/AD_IO/AD_IO.h \
		../Sandbox/AD_IO/AD_IO_Types.h \
		../Sandbox/AD_IO/autoInhibit.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/AD_IO/deviceInhibit.h \
		../Sandbox/AD_IO/logicSignals.h \
		../Sandbox/AD_IO/io_signal.h \
		../Sandbox/AD_IO/signal.h \
		../Sandbox/AD_IO/io_object.h \
		../Sandbox/Utilities/Mutex.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/AD_IO/dataPoint.h \
		../Sandbox/Utilities/utilities.h \
		../Sandbox/AD_IO/timeStampedSignal.h \
		../Sandbox/AD_IO/autoInhibitDevice.h \
		../Sandbox/AD_IO/currentOutputDevice.h \
		../Sandbox/AD_IO/SignalTypes.h \
		../Sandbox/AD_IO/analogSignals.h \
		../Sandbox/AD_IO/counterSignals.h \
		../Sandbox/AD_IO/DeviceTypes.h \
		../Sandbox/AD_IO/device.h \
		../Sandbox/AD_IO/inputDevice.h \
		../Sandbox/AD_IO/outputDevice.h \
		../Sandbox/AD_IO/fileLogger.h \
		../Sandbox/AD_IO/outputToScreen.h \
		../Sandbox/AD_IO/vectorCurrentOutput.h \
		../Sandbox/AD_IO/voltageInputDevice.h \
		../Sandbox/AD_IO/voltageOutputDevice.h \
		../Sandbox/AD_IO/SensorTypes.h \
		../Sandbox/AD_IO/sensors.h \
		../Sandbox/AD_IO/forceSensor.h \
		../Sandbox/AD_IO/forceSensorVector.h \
		../Sandbox/AD_IO/torqueSensor.h \
		../Sandbox/AD_IO/torqueSensorVector.h \
		../Sandbox/AD_IO/distanceSensor.h \
		../Sandbox/AD_IO/distanceSensorVector.h \
		../Sandbox/Utilities/Magnetics.h \
		../Sandbox/Producers/FieldProducer.h \
		../Sandbox/Producers/ConstMomentFieldProducer.h \
		../Sandbox/Producers/MomentProducer.h \
		../Sandbox/Producers/RotatingMomentProducer.h \
		../Sandbox/Producers/Configuration6DOF_Producer.h \
		../Sandbox/Producers/PositionProducer.h \
		../Sandbox/Producers/OrientationProducer.h \
		../Sandbox/Producers/VectorTemperature_Producer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/Omnimagnet.o ../Sandbox/Devices/Omnimagnet.cpp

BIN/moc_mainwindow.o: BIN/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/moc_mainwindow.o BIN/moc_mainwindow.cpp

BIN/moc_InterfaceButtons.o: BIN/moc_InterfaceButtons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/moc_InterfaceButtons.o BIN/moc_InterfaceButtons.cpp

BIN/moc_NumberWithUnits.o: BIN/moc_NumberWithUnits.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BIN/moc_NumberWithUnits.o BIN/moc_NumberWithUnits.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

